language: java
jdk: oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: il+g05jPRhzclcq+KIDUj3xYpI7X07P1cNaQuU805SHTOQgs9ctLFmYa23tQbwuK15mdOF/QYN0miRANdiKSyK/euiA04UCkeTUx80OIPG5mRAGBAfE+H0aZGg7xriaMHYhcBfl9W+Xy6lZEyzMryHd72wppFMUDxS9AK2Tt1OGigtfl9HGAJZrGoVMeaRDCr0oxb1wtsgdKSdFjn86aOruG1LpnHlzEcPbrRzjWCBGjvTIMIlXeWcjS9oiAw6p3GsF0uP26U1dAN5eCnhj9rXchjdq5xuDrFJc5IBcs/f0EGqE2J6kCHT+7kdG6qKumVpyLgjorpHXGxHTcB3gHR9wTYCQsYcwCCjee4FoeGnwDT/lrUqtm8m2V9sYP9mKT+yoe8xKCTqWe9rGJiSE99meX5p7qHF4X634ykUSNEPSbpXamC7tBAZLVgbam2rvsPRFhYOt5IqZXrhMaXyzW0R9bzZxWgxl+QRv5TQw0fd8hCDVl3Ynj74o/vF8Fn95DFCHKlByK4EZA/+ivsBYvRWNKl1BsDd6BmYzZ4TDq1dw6fgtN9IJdKd+mNKpMXCoPXFyNEh6l839wjT3PwyzPHLyDwer9LVKuKhB1AkwK6nLbtMlG+mJSWI4VETZLvDT9WeCWfZW2UbqUMkxaNCvBFe+SkJa+GJSVCiPhVf751/8=
  file: target/gnuob-soap.war
  on:
    tags: true